version: '3'

services:
  thoron:
    container_name: thoron
    image: thoron:alpine
    build:
      context: ./Thoron
      dockerfile: ./docker/Dockerfile
    depends_on:
      - meneldor
    environment:
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: meneldor
      DATABASE_DB: ${POSTGRES_DB}
    volumes:
      - ./Thoron:/app/src
    ports:
      - "8080:8000"
    entrypoint: ./docker/entrypoint.sh
    tty: true
    restart: always

  gwaihir:
    container_name: gwaihir
    build:
      context: ./Gwaihir
      dockerfile: ./Dockerfile
    environment:
      THORON_ADDR: http://thoron:8000
    volumes:
      - ./Gwaihir:/usr/src/app
    ports:
      - "80:1337"
    restart: always

  meneldor:
    container_name: meneldor
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - "./Meneldor/postgres-data:/var/lib/postgresql/data"
    ports:
      - "5000:5432"
    restart: always
